# Generated by Django 3.2.6 on 2021-08-27 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='placeFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('slot_one', models.IntegerField()),
                ('slot_two', models.IntegerField()),
                ('slot_three', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='placeOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('slot_one', models.IntegerField()),
                ('slot_two', models.IntegerField()),
                ('slot_three', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='placethree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('slot_one', models.IntegerField()),
                ('slot_two', models.IntegerField()),
                ('slot_three', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='placeTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('slot_one', models.IntegerField()),
                ('slot_two', models.IntegerField()),
                ('slot_three', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('user_dob', models.DateField()),
                ('aadhar_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.IntegerField()),
                ('first_dose', models.BooleanField()),
                ('first_dose_place', models.CharField(max_length=100)),
                ('first_dose_slot', models.CharField(max_length=100)),
                ('first_dose_date', models.DateField()),
                ('second_dose', models.BooleanField()),
                ('second_dose_place', models.CharField(max_length=100)),
                ('second_dose_slot', models.CharField(max_length=100)),
                ('second_dose_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.registration')),
            ],
        ),
    ]
