# Generated by Django 3.2.6 on 2021-08-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_dose_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
