# Generated by Django 3.2.6 on 2021-08-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_alter_user_first_dose_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placefour',
            name='slot_one',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placefour',
            name='slot_three',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placefour',
            name='slot_two',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placeone',
            name='slot_one',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placeone',
            name='slot_three',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placeone',
            name='slot_two',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placethree',
            name='slot_one',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placethree',
            name='slot_three',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placethree',
            name='slot_two',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placetwo',
            name='slot_one',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placetwo',
            name='slot_three',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placetwo',
            name='slot_two',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_dose',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_dose_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_dose_slot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_dose',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_dose_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_dose_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_dose_slot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
