# Generated by Django 3.2.6 on 2021-08-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_alter_registration_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_number',
            field=models.CharField(max_length=150),
        ),
    ]
