# Generated by Django 3.2.6 on 2021-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0007_auto_20210827_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placefour',
            name='id',
        ),
        migrations.RemoveField(
            model_name='placeone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='placethree',
            name='id',
        ),
        migrations.RemoveField(
            model_name='placetwo',
            name='id',
        ),
        migrations.AlterField(
            model_name='placefour',
            name='vaccination_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placeone',
            name='vaccination_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placethree',
            name='vaccination_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placetwo',
            name='vaccination_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
