# Generated by Django 3.2.6 on 2021-08-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0009_auto_20210827_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='register_number',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
